### ISSUE TITLE
The github action fails if there is an existing comment on the PR

### ISSUE THREAD

**Issue by gokhalesamruddhi** [RoryQ/checkmate#27]
In my use case, I'd like to check if a certain files have been newly added and then display a different checklist. I've achieved it by using tj-actions/changed-files@v44. It works fine by adding a checklist comment and the checklist checker modifies that comment and adds additional comments on the top. But there is an error at the end of the checklist checker github action saying list index out of bounds.
Is there any resolution to this?

**Comment by RoryQ** [comment]
Do you have a reproduceable example in a public repo? I think I have seen this error when there is no checklist found.

**Comment by gokhalesamruddhi** [comment]
Hi @RoryQ , looks like the issue is fixed now. Thanks a lot :)
